const express = require('express');
const router = express.Router();
const usercontroller = require('../controllers/user.controller');
const authmiddleware = require('../auth-middleware/auth');
router.post('/register', usercontroller.registerUser);
router.post('/login', usercontroller.loginUser);
router.get('/profile', authmiddleware.authUser, usercontroller.getuserProfile);
router.get('/logout', authmiddleware.authUser, usercontroller.logout);
router.put('/block-course', authmiddleware.authUser, usercontroller.blockedCourse);
router.post('/send-otp', usercontroller.forgotPassword);
router.post('/verify-otp', usercontroller.verifyOTP);
router.put('/update-password', usercontroller.createNewPassword);
router.get('/user-card-details', authmiddleware.optionalAuthUser, usercontroller.getusercardDetails);
router.get('/search-users', authmiddleware.optionalAuthUser, usercontroller.getUsersByName);
router.get('/other-user-profile/:userId', authmiddleware.optionalAuthUser, usercontroller.getOtherUserProfile);
module.exports = router;